#Bora Mutluoglu | bmutluog | 1564633 | cs12M | January 10, 2018 |
#Makefile for charType.c, creates an executable binary file
#of charType

charType : charType.o
	gcc -o charType charType.o

charType.o : charType.c
	gcc -c -std=c99 -Wall charType.c

clean :
	rm -f charType charType.o

