#Bora Mutluoglu | bmutluog | 1564633 | cs12M | January 2, 2018 |
#Makefile for FileReverse.c, creates an executable binary file
#of FileReverseFileReverse : FileReverse.o	gcc -o FileReverse FileReverse.o
FileReverse.o : FileReverse.c	gcc -c –std=c99 -Wall FileReverse.c
clean :	rm -f FileReverse FileReverse.o